import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Button, message, Table, Tag } from "antd";
import {
  CalendarOutlined,
  DashOutlined,
  DeleteOutlined,
  EditOutlined,
  FormOutlined,
  PlusOutlined,
  RobotOutlined,
  WhatsAppOutlined,
} from "@ant-design/icons";

export default function Home() {
  const [messageApi, contextHolder] = message.useMessage();
  const key = "updatable";

  const openMessage = (text: string) => {
    messageApi.open({
      key,
      type: "loading",
      content: `Redirect to ${text}...`,
      style: { marginTop: "40%" },
    });
    setTimeout(() => {
      messageApi.open({
        key,
        type: "success",
        content: "Done!",
        duration: 2,
        style: { marginTop: "40%" },
      });
    }, 1500);
  };

  const columns = [
    {
      title: "Título",
      dataIndex: "title",
      key: "title",
      width: "25%",
      ellipsis: true,
    },
    {
      title: "Descrição",
      dataIndex: "description",
      key: "description",
      width: "25%",
    },
    {
      title: "Tipo",
      dataIndex: "type",
      width: "15%",
      key: "type",
      render: function customRender(type: string) {
        const getTag: any = {
          Menu: <b>Menu</b>,
          Calendly: (
            <Tag icon={<CalendarOutlined />} color="#108ee9">
              Calendly
            </Tag>
          ),
          Intercom: (
            <Tag icon={<RobotOutlined />} color="#2db7f5">
              Intercom
            </Tag>
          ),
          Typeform: (
            <Tag icon={<FormOutlined />} color="#3b5999">
              Typeform
            </Tag>
          ),
          WhatsApp: (
            <Tag icon={<WhatsAppOutlined />} color="#87d068">
              WhatsApp
            </Tag>
          ),
        };
        return getTag[type];
      },
    },
    {
      width: "20%",
      align: "right",
      render: function customRender(row) {
        return (
          <div>
            <Button icon={<PlusOutlined />} type="text" onClick={() => openMessage('create')} disabled={row.type != "Menu"}/>
            <Button icon={<EditOutlined />} type="text" onClick={() => openMessage('edit')} />
            <Button icon={<DeleteOutlined />} type="text" onClick={() => openMessage('delete')} />
            <Button icon={<DashOutlined />} type="text" />
          </div>
        );
      },
    },
  ];

  const data = [
    {
      key: 1,
      title: "Agendar Consulta",
      description: "Agendamento de consultas",
      type: "Menu",
      children: [
        {
          key: 11,
          title: "Dúvidas",
          description: "Dúvidas sobre agendamento de consultas",
          type: "WhatsApp",
        },
        {
          key: 12,
          title: "Consulta Médica",
          description: "Consulta com médico",
          type: "Menu",
          children: [
            {
              key: 121,
              title: "Dra. Roberta Pessoa",
              description: "Agendamento com Dra. Roberta Pessoa",
              type: "Calendly",
            },
          ],
        },
        {
          key: 13,
          title: "Consulta de Saúde Mental",
          description: "Orientações e consultas",
          type: "Menu",
          children: [
            {
              key: 131,
              title: "Consulta Psicólogo",
              description: "Agendamento de consultas",
              type: "Menu",
              children: [
                {
                  key: 1311,
                  title: "Dr. Roberto Coelho",
                  description: "Agendamento com Dr. Roberto Coelho",
                  type: "Typeform",
                },
                {
                  key: 1312,
                  title: "Dr. Paulo Gomes",
                  description: "Agendamento com Dr. Paulo Gomes",
                  type: "Intercom",
                },
              ],
            },
          ],
        },
      ],
    },
    {
      key: 2,
      title: "Contato Rápido com Time de Saúde",
      description: "Contato Rápido",
      type: "WhatsApp",
    },
  ];
  return (
    <div>
      {contextHolder}
      <Head>
        <title>PoC - Nested Table Rows</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <p>Grupo 3778 - Serviços</p>
        <div>
          <Table
            style={{ width: "1200px" }}
            columns={columns}
            dataSource={data}
            pagination={false}
            size="large"
          />
        </div>
      </main>
    </div>
  );
}
